version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: reports_db
    ports:
      - "3306:3306"
    volumes:
      - ./radiologist_backend/MySQL/database.sql:/docker-entrypoint-initdb.d/data.sql

  frontend:
    image: node:16-alpine
    command: npm run dev
    volumes:
      - ./rrs_frontend:/app
    ports:
      - "3000:3000"
