version: "3.9"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    